// packages/react/src/library/components/NodeButton/NodeButton.tsx
import React from 'react';

export type NodeButtonProps = {
  text: string;
  color?: string;
  background?: string;
  onClick?: () => void;
};

const NodeButton = ({ text, color, background, onClick }: NodeButtonProps) => (
  <button
    className="function-junctions-node_button"
    style={{
      color,
      background,
    }}
    onClick={onClick}
  >
    {text}
  </button>
);

export default NodeButton;

// src/library/components/Node/components/NodeButton/NodeButton.svelte
<script lang="ts">

  export let text: string;
  export let color: string | undefined = undefined;
  export let background: string | undefined = undefined;
</script>

<style lang="scss" global>
  @import './NodeButton.scss';
</style>

<button
  class="function-junctions-node_button"
  style={`
    ${color ? `color: ${color};` : ''}
    ${background ? `background: ${background}` : ''}`
  }
  on:click
>
  {text}
</button>
