// src/library/components/ContextMenu/ContextMenu.svelte
<style lang="scss" global>
  @import './ContextMenu.scss';
</style>

<script lang="ts">
import { onDestroy } from 'svelte';

import type { Unsubscriber } from 'svelte/store';


import { ContextMenu } from '.';

export let containerRef: HTMLDivElement;
export let ref: HTMLDivElement | undefined = undefined;

export let instance: ContextMenu | undefined = undefined;

export let opened = false;

let unsubscribe: Unsubscriber;

$: (() => {
  if (ref) {
    instance = new ContextMenu(ref, containerRef);
    const { opened: value } = instance;

    unsubscribe = value.subscribe((isOpened) => {
      opened = isOpened;
    });
  }

})();

onDestroy(() => {
  unsubscribe();
});
</script>

<div
  class="function-junctions-context_menu"
  bind:this={ref}
>
  <slot />
</div>

// packages/react/src/library/ContextMenu/ContextMenu.tsx
import {
  ContextMenu as ContextMenuType,
  ContextMenu as ContextMenuClass,
} from '@function-junctions/core';
import React from 'react';

export type ContextMenuProps = {
  containerRef: React.RefObject<HTMLDivElement>;
  instance: ContextMenuType | undefined;
  setInstance: React.Dispatch<React.SetStateAction<ContextMenuType | undefined>>;
  onOpened: (opened: boolean) => void;
  children: React.ReactNode;
};

const ContextMenu = ({
  children,
  containerRef,
  instance,
  setInstance,
  onOpened,
}: ContextMenuProps) => {
  const ref = React.useRef<HTMLDivElement>(null);

  React.useEffect(() => {
    if (ref && ref?.current && containerRef && containerRef.current) {
      if (!instance) {
        const contextMenuInstance = new ContextMenuClass(ref.current, containerRef.current);
        setInstance(contextMenuInstance);

        if (contextMenuInstance) {
          const { opened: value } = contextMenuInstance;

          value.subscribe((isOpened) => {
            onOpened(isOpened);
          });
        }
      } else {
        instance.scope = containerRef.current;
      }
    }
  }, [ref, setInstance, containerRef, instance, onOpened]);

  return (
    <div className="function-junctions-context_menu" ref={ref}>
      {children}
    </div>
  );
};

export default ContextMenu;
