// packages/svelte/src/library/components/ContextMenu/NodeContextMenu.svelte
<script lang="ts">
  import type { Editor } from 'core/components/Editor';

  import type {
    ContextMenu as ContextMenuType,
    NodeContextMenuBlueprint,
  } from 'core/components/ContextMenu';
  import ContextMenu from './ContextMenu.svelte';
  import ContextMenuItem from './ContextMenuItem.svelte';

  export let ids: string[];

  export let editorInstance: Editor;
  export let instance: ContextMenuType | undefined = undefined;

  export let contextMenu: NodeContextMenuBlueprint;

  export let containerRef: HTMLDivElement;

  export let opened = false;
</script>

<ContextMenu {containerRef} bind:instance bind:opened>
  <ul on:click={() => instance?.close()}>
    {#if contextMenu.items && instance}
      {#each contextMenu.items as item}
        <ContextMenuItem {item} {ids} contextMenu={instance} editor={editorInstance} />
      {/each}
    {/if}
  </ul>
</ContextMenu>

// packages/react/src/library/ContextMenu/NodeContextMenu.tsx
import React from 'react';

import {
  NodeContextMenuBlueprint,
  ContextMenu as ContextMenuClass,
} from 'core/components/ContextMenu';
import ContextMenuItem from './ContextMenuItem';
import ContextMenu from './ContextMenu';
import { ReactEditor } from '../Editor';

export type NodeContextMenuProps = {
  ids: string[];
  editorInstance: ReactEditor;
  instance: ContextMenuClass | undefined;
  contextMenu: NodeContextMenuBlueprint;
  containerRef: React.RefObject<HTMLDivElement>;
  setInstance: React.Dispatch<React.SetStateAction<ContextMenuClass | undefined>>;
  onOpened: (opened: boolean) => void;
};

const NodeContextMenu = ({
  ids,
  editorInstance,
  instance,
  contextMenu,
  containerRef,
  setInstance,
  onOpened,
}: NodeContextMenuProps) => {
  return (
    <ContextMenu
      containerRef={containerRef}
      instance={instance}
      setInstance={setInstance}
      onOpened={onOpened}
    >
      <ul onClick={() => instance?.close()}>
        {contextMenu.items && instance && (
          <>
            {contextMenu.items.map((item) => {
              <ContextMenuItem
                item={item}
                ids={ids}
                contextMenu={instance}
                editor={editorInstance}
              />;
            })}
          </>
        )}
      </ul>
    </ContextMenu>
  );
};

export default NodeContextMenu;
