// packages/react/src/library/Connection/Connection.tsx
import React from 'react';
import { createConnectionPath } from 'core/components/Connection';
import { Point } from 'core/index';

export type ConnectionProps = {
  connection: { p1: Point; p2: Point };
};

const Connection = ({ connection }: ConnectionProps) => {
  const ref = React.useRef<SVGSVGElement>(null);

  React.useEffect(() => {
    if (ref.current) createConnectionPath(ref.current, { p1: connection.p1, p2: connection.p2 });
  }, [ref, connection.p1, connection.p2]);

  return <svg className="function-junctions-connection" ref={ref} />;
};

export default Connection;

// packages/svelte/src/library/components/Connection/Connection.svelte
<script lang="ts">
  import type { Point } from 'core/index';
  import { createConnectionPath } from 'core/components/Connection';

  export let connection: { p1: Point; p2: Point };

  let ref: SVGSVGElement;

  $: createConnectionPath(ref, { p1: connection.p1, p2: connection.p2 });
</script>

<svg class="function-junctions-connection" bind:this={ref} />
