// src/library/components/Node/Node.svelte
<style lang="scss" global>
  @import './Node.scss';
</style>

<script lang="ts">
  import type { SvelteComponentDev } from 'svelte/internal';
  import type { Point } from '../../types';
  import type { Editor } from '../Editor';
  
  import type {
    InputSockets,
    OutputSockets,
    InputSocket,
    OutputSocket,
  } from '../Sockets';
  import type { NodeControlButtons } from '.';

  import NodeButton from './components/NodeButton/NodeButton.svelte';
  import Socket from '../Socket/Socket.svelte';
  
  export let title: string;
  export let id: string;

  export let inputs: InputSockets<Record<string, InputSocket<any>>> | undefined;
  export let outputs: OutputSockets<Record<string, OutputSocket<any>>> | undefined;
  export let color: string | undefined = undefined;
  export let className: string | undefined = undefined;
  export let style: string | undefined = undefined;

  export let component: typeof SvelteComponentDev;
  export let coordinates: Point;

  export let nodeControlButtons: NodeControlButtons | boolean;

  export let deletable: boolean | undefined = undefined;
  export let cloneable: boolean | undefined = undefined;

  export let selected = false;

  export let store: Record<string, unknown> | undefined;

  export let editor: Editor;
</script>

<div
  class={`function-junctions-node ${selected ? 'function-junctions-node-selected' : ''} ${className ?? ''}`}
  style={`${style ? `${style};` : ''} transform: translate(${coordinates.x}px, ${coordinates.y}px)`}
  on:click
  on:mousedown
  on:touchstart
  on:contextmenu
>
  {#if cloneable ?? ((typeof nodeControlButtons === 'boolean' && nodeControlButtons)
    || (typeof nodeControlButtons === 'object' && nodeControlButtons.clone))
  }
    <div class="function-junctions-node-header">
      <NodeButton
        text="Clone"
        on:click={() => editor.cloneNode(id, { x: coordinates.x + 50, y: coordinates.y + 50 })}
      />
    </div>
  {/if}
  <div class="function-junctions-node-title" style={`background: ${color ?? 'linear-gradient(#228cfd, #007aff)'}`}>{title}</div>
  <div class="function-junctions-node-content">
    {#if outputs}
      <div class="function-junctions-node-outputs">
        {#each Object.keys(outputs) as key}
          <Socket
            title={key}
            type="output"
            id={key}
            nodeId={id}
            color={outputs[key].color}
            socketType={outputs[key].type}
            disabled={outputs[key].disabled}
            {editor}
          />
        {/each}
      </div>
    {/if}
    <div class="function-junctions-node-content">
      <svelte:component
        this={component}
        {title}
        {id}
        {editor}
        bind:store
        bind:inputs
        bind:outputs
      />
    </div>
    {#if inputs}
      <div class="function-junctions-node-inputs">
        {#each Object.keys(inputs) as key}
          <Socket
            title={key}
            type="input"
            id={key}
            nodeId={id}
            socketType={inputs[key].type}
            color={inputs[key].color}
            disabled={inputs[key].disabled}
            {editor}
          />
        {/each}
      </div>
    {/if}
  </div>
  {#if deletable ?? ((typeof nodeControlButtons === 'boolean' && nodeControlButtons)
    || (typeof nodeControlButtons === 'object' && nodeControlButtons.delete))
  }
    <div class="function-junctions-node-footer">
      <NodeButton
        text="Delete"
        color="rgb(255, 59, 48)"
        on:click={() => editor.deleteNode(id)}
      />
    </div>
  {/if}
</div>

// packages/react/src/library/Node/Node.tsx
import React from 'react';
import { NodeControlButtons } from 'core/components/NodeButton';
import { InputSocket, OutputSocket, Point } from 'core/types';
import NodeButton from '../NodeButton/NodeButton';
import Socket from '../Socket/Socket';
import { NodeProps } from 'core/components/Node';
import { ReactEditor } from '../Editor';

export type NodeContainerProps = {
  title: string;
  id: string;
  inputs: Record<string, InputSocket<any>> | undefined;
  outputs: Record<string, OutputSocket<any>> | undefined;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  component: React.ComponentClass<NodeProps<React.ComponentClass<NodeProps<React.ComponentClass>>>>;
  coordinates: Point;
  nodeControlButtons: NodeControlButtons | boolean;
  deletable?: boolean;
  cloneable?: boolean;
  selected?: boolean;
  store?: Record<string, unknown>;
  editor: ReactEditor;
  onClick?: () => void;
  onMouseDown?: () => void;
  onTouchStart?: () => void;
  onContextMenu?: () => void;
};

const Node = ({
  title,
  id,
  inputs,
  outputs,
  color,
  className,
  style,
  component: Component,
  coordinates,
  nodeControlButtons,
  deletable,
  cloneable,
  selected,
  store = {},
  editor,
  onClick,
  onMouseDown,
  onTouchStart,
  onContextMenu,
}: NodeContainerProps) => (
  <>
    <div
      className={`function-junctions-node ${selected ? 'function-junctions-node-selected' : ''} ${
        className ?? ''
      }`}
      style={{ ...style, transform: `translate(${coordinates.x}px, ${coordinates.y}px)` }}
      onClick={onClick}
      onMouseDown={onMouseDown}
      onTouchStart={onTouchStart}
      onContextMenu={onContextMenu}
    >
      {cloneable ??
      ((typeof nodeControlButtons === 'boolean' && nodeControlButtons) ||
        (typeof nodeControlButtons === 'object' && nodeControlButtons.clone)) ? (
        <div className="function-junctions-node-header">
          <NodeButton
            text="Clone"
            onClick={() => editor.cloneNode(id, { x: coordinates.x + 50, y: coordinates.y + 50 })}
          />
        </div>
      ) : (
        <></>
      )}
      <div
        className="function-junctions-node-title"
        style={{ background: `${color ?? 'linear-gradient(#228cfd, #007aff)'}` }}
      >
        {title}
      </div>
      <div className="function-junctions-node-content">
        {outputs ? (
          <div className="function-junctions-node-outputs">
            {Object.keys(outputs).map((key) => (
              <Socket
                title={key}
                key={key}
                type="output"
                id={key}
                nodeId={id}
                color={outputs[key].color}
                socketType={outputs[key].type}
                disabled={outputs[key].disabled}
                editor={editor}
              />
            ))}
          </div>
        ) : (
          <></>
        )}
        <div className="function-junctions-node-content">
          <Component
            title={title}
            id={id}
            editor={editor}
            store={store}
            inputs={inputs}
            outputs={outputs}
          />
        </div>
        {inputs ? (
          <div className="function-junctions-node-inputs">
            {Object.keys(inputs).map((key) => (
              <Socket
                title={key}
                key={key}
                type="input"
                id={key}
                nodeId={id}
                socketType={inputs[key].type}
                color={inputs[key].color}
                disabled={inputs[key].disabled}
                editor={editor}
              />
            ))}
          </div>
        ) : (
          <></>
        )}
      </div>
      {deletable ??
      ((typeof nodeControlButtons === 'boolean' && nodeControlButtons) ||
        (typeof nodeControlButtons === 'object' && nodeControlButtons.delete)) ? (
        <div className="function-junctions-node-footer">
          <NodeButton
            text="Delete"
            color="rgb(255, 59, 48)"
            onClick={() => editor.deleteNode(id)}
          />
        </div>
      ) : (
        <></>
      )}
    </div>
  </>
);

export default Node;
