// packages/components/src/components/Node/Node.svelte
<script lang="ts">
  import { SvelteComponentDev } from 'svelte/internal';
  import { Point } from '../../types';

  import './Node.scss';

  import { InputSocket, OutputSocket } from '../Socket';
  import { InputSockets, OutputSockets } from '../Sockets';

  import Socket from '../Socket/Socket.svelte';
import { nodesState } from '../Nodes/store';
  
  export let title: string;
  export let id: string;

  export let inputs: InputSockets<Record<string, InputSocket<any>>> | undefined;
  export let outputs: OutputSockets<Record<string, OutputSocket<any>>> | undefined;
  export let color: string | undefined = undefined;

  export let component: typeof SvelteComponentDev;
  export let coordinates: Point;

  export let selected = false;

  export let store: Record<string, unknown> | undefined = $nodesState[id].store;

  $: $nodesState[id].store = store;
</script>

<div
  class={`function-junction-node ${selected ? 'function-junction-node-selected' : ''}`}
  style={`transform: translate(${coordinates.x}px, ${coordinates.y}px)`}
  on:click
  on:mousedown
  on:contextmenu
>
  <div class="function-junction-node-title" style={`background: ${color ?? 'linear-gradient(#228cfd, #007aff)'}`}>{title}</div>
  <div class="function-junction-node-content">
    {#if outputs}
      <div class="function-junction-node-outputs">
        {#each Object.keys(outputs) as key}
          <Socket
            title={key}
            type="output"
            id={key}
            nodeId={id}
            color={outputs[key].color}
          />
        {/each}
      </div>
    {/if}
    <div class="function-junction-node-content">
      <svelte:component
        this={component}
        {inputs}
        {outputs}
        bind:store
      />
    </div>
    {#if inputs}
      <div class="function-junction-node-inputs">
        {#each Object.keys(inputs) as key}
          <Socket
            title={key}
            type="input"
            id={key}
            nodeId={id}
            color={inputs[key].color}
          />
        {/each}
      </div>
    {/if}
  </div>
</div>

// packages/react/src/library/Node/Node.tsx
import React from 'react';
import { NodeControlButtons } from 'core/components/NodeButton';
import { InputSocket, OutputSocket, Point } from 'core/types';
import NodeButton from '../NodeButton/NodeButton';
import Socket from '../Socket/Socket';
import { NodeProps } from 'core/components/Node';
import { ReactEditor } from '../Editor';

export type NodeContainerProps = {
  title: string;
  id: string;
  inputs: Record<string, InputSocket<any>> | undefined;
  outputs: Record<string, OutputSocket<any>> | undefined;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  component: React.ComponentClass<NodeProps<React.ComponentClass<NodeProps<React.ComponentClass>>>>;
  coordinates: Point;
  nodeControlButtons: NodeControlButtons | boolean;
  deletable?: boolean;
  cloneable?: boolean;
  selected?: boolean;
  store?: Record<string, unknown>;
  editor: ReactEditor;
  onClick?: () => void;
  onMouseDown?: () => void;
  onTouchStart?: () => void;
  onContextMenu?: () => void;
};

const Node = ({
  title,
  id,
  inputs,
  outputs,
  color,
  className,
  style,
  component: Component,
  coordinates,
  nodeControlButtons,
  deletable,
  cloneable,
  selected,
  store = {},
  editor,
  onClick,
  onMouseDown,
  onTouchStart,
  onContextMenu,
}: NodeContainerProps) => (
  <>
    <div
      className={`function-junctions-node ${selected ? 'function-junctions-node-selected' : ''} ${
        className ?? ''
      }`}
      style={{ ...style, transform: `translate(${coordinates.x}px, ${coordinates.y}px)` }}
      onClick={onClick}
      onMouseDown={onMouseDown}
      onTouchStart={onTouchStart}
      onContextMenu={onContextMenu}
    >
      {cloneable ??
      ((typeof nodeControlButtons === 'boolean' && nodeControlButtons) ||
        (typeof nodeControlButtons === 'object' && nodeControlButtons.clone)) ? (
        <div className="function-junctions-node-header">
          <NodeButton
            text="Clone"
            onClick={() => editor.cloneNode(id, { x: coordinates.x + 50, y: coordinates.y + 50 })}
          />
        </div>
      ) : (
        <></>
      )}
      <div
        className="function-junctions-node-title"
        style={{ background: `${color ?? 'linear-gradient(#228cfd, #007aff)'}` }}
      >
        {title}
      </div>
      <div className="function-junctions-node-content">
        {outputs ? (
          <div className="function-junctions-node-outputs">
            {Object.keys(outputs).map((key) => (
              <Socket
                title={key}
                key={key}
                type="output"
                id={key}
                nodeId={id}
                color={outputs[key].color}
                socketType={outputs[key].type}
                disabled={outputs[key].disabled}
                editor={editor}
              />
            ))}
          </div>
        ) : (
          <></>
        )}
        <div className="function-junctions-node-content">
          <Component
            title={title}
            id={id}
            editor={editor}
            store={store}
            inputs={inputs}
            outputs={outputs}
          />
        </div>
        {inputs ? (
          <div className="function-junctions-node-inputs">
            {Object.keys(inputs).map((key) => (
              <Socket
                title={key}
                key={key}
                type="input"
                id={key}
                nodeId={id}
                socketType={inputs[key].type}
                color={inputs[key].color}
                disabled={inputs[key].disabled}
                editor={editor}
              />
            ))}
          </div>
        ) : (
          <></>
        )}
      </div>
      {deletable ??
      ((typeof nodeControlButtons === 'boolean' && nodeControlButtons) ||
        (typeof nodeControlButtons === 'object' && nodeControlButtons.delete)) ? (
        <div className="function-junctions-node-footer">
          <NodeButton
            text="Delete"
            color="rgb(255, 59, 48)"
            onClick={() => editor.deleteNode(id)}
          />
        </div>
      ) : (
        <></>
      )}
    </div>
  </>
);

export default Node;
