// packages/svelte/src/library/components/Node/RawNode.svelte
<script lang="ts">
  import type { SvelteComponentDev } from 'svelte/internal';
  import type { Editor } from 'core/components/Editor';

  import type {
    InputSockets,
    OutputSockets,
    InputSocket,
    OutputSocket,
  } from 'core/components/Sockets';

  export let title: string;
  export let id: string;

  export let inputs: InputSockets<Record<string, InputSocket<any>>> | undefined;
  export let outputs: OutputSockets<Record<string, OutputSocket<any>>> | undefined;

  export let component: typeof SvelteComponentDev;
  export let store: Record<string, unknown> | undefined;

  export let editor: Editor;
</script>

<div class="function-junctions-raw-node">
  <div class="function-junctions-raw-node-content">
    <svelte:component this={component} {inputs} {outputs} {title} {id} {editor} bind:store />
  </div>
</div>

// packages/react/src/library/Node/RawNode.tsx
import React from 'react';

import { Editor, InputSocket, InputSockets, OutputSocket, OutputSockets } from 'core/types';
import { NodeProps } from './Node';

export type RawNodeProps = {
  title: string;
  id: string;
  inputs: InputSockets<Record<string, InputSocket<any>>> | undefined;
  outputs: OutputSockets<Record<string, OutputSocket<any>>> | undefined;
  component: React.ComponentClass<NodeProps>;
  store?: Record<string, unknown>;
  editor: Editor;
};

const RawNode = ({
  title,
  id,
  inputs,
  outputs,
  component: Component,
  store = {},
  editor,
}: RawNodeProps) => (
  <div className="function-junctions-raw-node">
    <div className="function-junctions-raw-node-content">
      <Component
        title={title}
        id={id}
        editor={editor}
        store={store}
        inputs={inputs}
        outputs={outputs}
      />
    </div>
  </div>
);

export default RawNode;
