// packages/kitchen-sink/src/components/NumberNode.svelte
<script lang="ts">
  import type { OutputSocket, OutputSockets } from '@function-junction/components/src/components';
  
  export let outputs: OutputSockets<{
    Number: OutputSocket<number>;
  }>;

  const { value } = outputs.Number;
</script>

<input type="number" bind:value={$value} />
<br />
<br />

// packages/react-playground/src/components/NumberNode.tsx
import React from 'react';
import { FJ } from '@function-junctions/react';

const NumberNode = ({
  outputs,
}: FJ.NodeProps<Record<string, never>, { Number: FJ.OutputSocket<number> }>) => {
  const { value, setValue } = outputs.Number;

  return (
    <input
      type="number"
      value={value}
      onChange={(event) => setValue(parseInt(event.currentTarget.value, 10))}
    />
  );
};

export default NumberNode;
