// packages/svelte/src/library/components/NodeButton/NodeButton.svelte
<script lang="ts">
  export let text: string;
  export let color: string | undefined = undefined;
  export let background: string | undefined = undefined;
</script>

<button
  class="function-junctions-node_button"
  style={`
    ${color ? `color: ${color};` : ''}
    ${background ? `background: ${background}` : ''}`}
  on:click
>
  {text}
</button>

// packages/react/src/library/NodeButton/NodeButton.tsx
import React from 'react';
import { NodeButtonProps } from 'core/components/NodeButton';

const NodeButton = ({ text, color, background, onClick }: NodeButtonProps) => (
  <button
    className="function-junctions-node_button"
    style={{
      color,
      background,
    }}
    onClick={onClick}
  >
    {text}
  </button>
);

export default NodeButton;
