// packages/react/src/library/components/Node/RawNode.tsx
import React from 'react';

import { InternalInputSocket, InternalNode, InternalOutputSocket } from 'core/index';
import { ReactComponent, Editor } from '../Editor';
import { Updater } from '../Hooks';

export type RawNodeProps = {
  title: string;
  id: string;
  inputs: Record<string, InternalInputSocket<any>> | undefined;
  outputs: Record<string, InternalOutputSocket<any>> | undefined;
  component: ReactComponent;
  store?: Record<string, unknown>;
  editor: Editor;
  updateNodes: Updater<
    Record<
      string,
      InternalNode<
        ReactComponent,
        React.CSSProperties,
        Record<string, InternalInputSocket<any>>,
        Record<string, InternalOutputSocket<any>>
      >
    >
  >;
};

const RawNode = ({
  title,
  id,
  inputs,
  outputs,
  component: Component,
  store = {},
  editor,
  updateNodes,
}: RawNodeProps) => {
  const [reactStore, setReactStore] = React.useState<Record<string, unknown>>(store);

  React.useEffect(() => {
    updateNodes((prevNodes) => ({
      ...prevNodes,
    }));
  }, [id, reactStore, updateNodes]);

  return (
    <div className="function-junctions-raw-node">
      <div className="function-junctions-raw-node-content">
        <Component
          title={title}
          id={id}
          editor={editor}
          store={store}
          inputs={inputs}
          outputs={outputs}
          setStore={setReactStore}
        />
      </div>
    </div>
  );
};

export default RawNode;

// packages/svelte/src/library/components/Node/RawNode.svelte
<script lang="ts">
  import type { SvelteComponentDev } from 'svelte/internal';

  import type { InputSocket, OutputSocket } from '@function-junctions/core';

  import type { SvelteEditor } from '../Editor';

  export let title: string;
  export let id: string;

  export let inputs: Record<string, InputSocket<any>> | undefined;
  export let outputs: Record<string, OutputSocket<any>> | undefined;

  export let component: typeof SvelteComponentDev;
  export let store: Record<string, unknown> | undefined;

  export let editor: SvelteEditor;
</script>

<div class="function-junctions-raw-node">
  <div class="function-junctions-raw-node-content">
    <svelte:component this={component} {inputs} {outputs} {title} {id} {editor} bind:store />
  </div>
</div>
