// packages/svelte/src/library/components/Nodes/Nodes.svelte
<script lang="ts">
  import {
    type EditorState,
    type NodeControlButtons,
    type ContextMenu,
    getMatrix,
    Interaction,
    Drag,
  } from 'core/index';
  import Node from '../Node/Node.svelte';
  import Connections from '../Connections/Connections.svelte';

  import type { EditorContextMenuProp, NodeContextMenuProp } from 'core/components/ContextMenu';
  import EditorContextMenu from '../ContextMenu/EditorContextMenu.svelte';
  import NodeContextMenu from '../ContextMenu/NodeContextMenu.svelte';
  import type { Editor } from '../Editor';
  import { onMount } from 'svelte';

  export let editor: Editor;
  export let state: EditorState | undefined;

  export let multiselect: boolean;
  export let zoomable: boolean;
  export let pannable: boolean;
  export let moveable: boolean;
  export let interactable: boolean;

  export let nodeControlButtons: NodeControlButtons | boolean;

  export let editorContextMenu: EditorContextMenuProp;
  export let nodeContextMenu: NodeContextMenuProp;

  export let onReady: ((editor: Editor) => void) | undefined = undefined;

  let ref: HTMLDivElement;

  const { position } = editor;
  const { current: nodes } = editor.nodes;
  const { restored: stateRestored, nodes: nodesState } = editor.state;
  const { show: showLiveConnection, state: liveConnectionState } = editor.connection;

  let editorContextMenuInstance: ContextMenu;
  let nodeContextMenuInstance: ContextMenu;

  const interaction = new Interaction(nodes, position, undefined, {
    multiselect,
    zoomable,
    pannable,
    moveable,
  });

  const hideLiveConnection = () => $liveConnectionState && ($showLiveConnection = false);

  $: $nodes,
    (() => {
      if (stateRestored) editor.updateState();
    })();

  $: $nodesState,
    $position,
    (state = {
      nodes: $nodesState,
      position: $position,
    });

  $: if (stateRestored && onReady) onReady(editor);

  onMount(() => {
    interaction.dragger = Drag({
      scaleSensitivity: 100,
      minScale: 0.1,
      maxScale: 30,
      element: ref,
      transformation: position,
    });
  });

  $: {
    interaction.editorContextMenu = (() => {
      if (typeof editorContextMenu === 'function')
        return { type: 'callback', callback: editorContextMenu };
      return {
        type: 'instance',
        instance: editorContextMenuInstance,
        blueprint: editorContextMenu,
      };
    })();

    interaction.nodeContextMenu = (() => {
      if (typeof nodeContextMenu === 'function')
        return { type: 'callback', callback: nodeContextMenu };
      return {
        type: 'instance',
        instance: nodeContextMenuInstance,
        blueprint: nodeContextMenu,
      };
    })();
  }
</script>

<div
  class="function-junctions-nodes"
  on:click={(event) => {
    hideLiveConnection();

    editorContextMenuInstance?.evaluate(event);
    nodeContextMenuInstance?.evaluate(event);
  }}
  on:wheel={interaction.zoom}
  on:mousedown={interaction.startDrag}
  on:mouseup={interaction.endDrag}
  on:mousemove={interaction.drag}
  on:touchstart={interaction.startDrag}
  on:touchend={interaction.endDrag}
  on:touchmove={interaction.touch}
  on:contextmenu={interaction.openEditorContextMenu}
>
  {#if editorContextMenu && typeof editorContextMenu !== 'function'}
    <EditorContextMenu
      containerRef={ref}
      contextMenu={editorContextMenu}
      bind:instance={editorContextMenuInstance}
      bind:editorInstance={editor}
      bind:opened={interaction.contextMenuOpen}
    />
  {/if}

  {#if nodeContextMenu && typeof nodeContextMenu !== 'function'}
    <NodeContextMenu
      containerRef={ref}
      contextMenu={nodeContextMenu}
      ids={interaction.selectedNodesIds}
      bind:instance={nodeContextMenuInstance}
      bind:editorInstance={editor}
      bind:opened={interaction.contextMenuOpen}
    />
  {/if}

  <div
    class="function-junctions-nodes-zoom"
    style={`
      transform-origin: ${$position.originX}px ${$position.originY}px;
      transform: ${getMatrix({
        scale: $position.scale,
        translateX: $position.translateX,
        translateY: $position.translateY,
      })};
      touch-action: none;
    `}
    bind:this={ref}
  >
    <Connections {editor} />
    {#each Object.keys($nodes) as key (key)}
      {#if $nodes[key] && $nodesState[key]}
        <Node
          title={$nodes[key].type}
          id={key}
          component={$nodes[key].component}
          inputs={$nodes[key].inputs}
          outputs={$nodes[key].outputs}
          coordinates={{
            x: $nodes[key].x,
            y: $nodes[key].y,
          }}
          color={$nodes[key].color}
          className={`${$nodes[key].className ?? ''} ${
            !interactable ? 'function-junction-node-disabled' : ''
          }`}
          style={$nodes[key].style ?? ''}
          selected={interaction.selectedNodesIds.some((selectedNodeId) => key === selectedNodeId)}
          cloneable={$nodes[key].cloneable}
          deletable={$nodes[key].deletable}
          {nodeControlButtons}
          {editor}
          bind:store={$nodesState[key].store}
          on:mousedown={(event) => interaction.dragNode(event, key)}
          on:touchstart={(event) => interaction.dragNode(event, key)}
          on:contextmenu={(event) => interaction.openNodeContextMenu(event, key)}
        />
      {/if}
    {/each}
  </div>
</div>

// packages/react/src/library/components/Nodes/Nodes.tsx
import React from 'react';
import {
  ContextMenu,
  EditorContextMenuProp,
  NodeContextMenuProp,
  NodeControlButtons,
  EditorState,
  Interaction,
  Drag,
  getMatrix,
} from 'core/index';
import { Editor } from '../Editor';
import { useReadable, useWritable } from '../Hooks';
import EditorContextMenu from '../ContextMenu/EditorContextMenu';
import Node from '../Node/Node';
import NodeContextMenu from '../ContextMenu/NodeContextMenu';
import Connections from '../Connections/Connections';

export type NodesProps = {
  editor: Editor;
  state: EditorState | undefined;
  setState: React.Dispatch<React.SetStateAction<EditorState | undefined>>;

  multiselect: boolean;
  zoomable: boolean;
  pannable: boolean;
  moveable: boolean;
  interactable: boolean;
  nodeControlButtons: NodeControlButtons | boolean;

  editorContextMenu: EditorContextMenuProp;
  nodeContextMenu: NodeContextMenuProp;

  onReady: ((editor: Editor) => void) | undefined;
};

const Nodes = ({
  editor,
  setState,
  multiselect,
  zoomable,
  pannable,
  moveable,
  interactable,
  nodeControlButtons,
  editorContextMenu,
  nodeContextMenu,
  onReady,
}: NodesProps) => {
  const ref = React.useRef<HTMLDivElement>(null);

  const { position: positionStore } = editor;
  const { current: nodesStore } = editor.nodes;
  const { restored: stateRestoredStore, nodes: nodesStateStore } = editor.state;
  const { show: showLiveConnectionStore, state: liveConnectionStateStore } = editor.connection;

  const position = useReadable(positionStore);
  const [nodes, , updateNodes] = useWritable(nodesStore);

  const stateRestored = useReadable(stateRestoredStore);
  const nodesState = useReadable(nodesStateStore);

  const [, setShowLiveConnection] = useWritable(showLiveConnectionStore);
  const liveConnectionState = useReadable(liveConnectionStateStore);

  const [interaction] = React.useState(
    new Interaction(nodesStore, positionStore, undefined, {
      multiselect,
      zoomable,
      pannable,
      moveable,
    }),
  );

  const [editorContextMenuInstance, setEditorContextMenuInstance] = React.useState<ContextMenu>();
  const [nodeContextMenuInstance, setNodeContextMenuInstance] = React.useState<ContextMenu>();

  const hideLiveConnection = React.useCallback(
    () => liveConnectionState && setShowLiveConnection(false),
    [liveConnectionState, setShowLiveConnection],
  );

  React.useEffect(() => {
    if (stateRestored) editor.updateState();
  }, [nodes, stateRestored, editor]);

  React.useEffect(
    () =>
      setState({
        nodes: nodesState,
        position,
      }),
    [position, setState],
  );

  React.useEffect(() => {
    if (stateRestored && onReady) onReady(editor);
  }, [onReady, editor, stateRestored]);

  React.useEffect(() => {
    if (ref.current)
      interaction.dragger = Drag({
        scaleSensitivity: 100,
        minScale: 0.1,
        maxScale: 30,
        element: ref.current,
        transformation: positionStore,
      });
  }, [interaction, positionStore, ref]);

  React.useEffect(() => {
    if (editorContextMenuInstance && editorContextMenu)
      interaction.editorContextMenu = (() => {
        if (typeof editorContextMenu === 'function')
          return { type: 'callback', callback: editorContextMenu };
        return {
          type: 'instance',
          instance: editorContextMenuInstance,
          blueprint: editorContextMenu,
        };
      })();
    if (nodeContextMenuInstance && nodeContextMenu)
      interaction.nodeContextMenu = (() => {
        if (typeof nodeContextMenu === 'function')
          return { type: 'callback', callback: nodeContextMenu };
        return {
          type: 'instance',
          instance: nodeContextMenuInstance,
          blueprint: nodeContextMenu,
        };
      })();
  }, [
    editorContextMenu,
    editorContextMenuInstance,
    interaction,
    nodeContextMenu,
    nodeContextMenuInstance,
  ]);

  React.useEffect(() => {
    interaction.nodes = nodesStore;
    interaction.position = positionStore;
  }, [interaction, nodesStore, positionStore]);

  return (
    <div
      className="function-junctions-nodes"
      onClick={(event) => {
        hideLiveConnection();

        editorContextMenuInstance?.evaluate(event.nativeEvent);
        nodeContextMenuInstance?.evaluate(event.nativeEvent);
      }}
      onWheel={({ nativeEvent }) => interaction.zoom(nativeEvent)}
      onMouseDown={({ nativeEvent }) => interaction.startDrag(nativeEvent)}
      onMouseUp={interaction.endDrag}
      onMouseMove={({ nativeEvent }) => interaction.drag(nativeEvent)}
      onTouchStart={({ nativeEvent }) => interaction.startDrag(nativeEvent)}
      onTouchEnd={interaction.endDrag}
      onTouchMove={({ nativeEvent }) => interaction.touch(nativeEvent)}
      onContextMenu={({ nativeEvent }) => interaction.openEditorContextMenu(nativeEvent)}
    >
      {editorContextMenu && typeof editorContextMenu !== 'function' && (
        <EditorContextMenu
          containerRef={ref}
          contextMenu={editorContextMenu}
          instance={editorContextMenuInstance}
          setInstance={setEditorContextMenuInstance}
          editorInstance={editor}
          onOpened={(opened) => {
            interaction.contextMenuOpen = opened;
          }}
        />
      )}

      {nodeContextMenu && typeof nodeContextMenu !== 'function' && (
        <NodeContextMenu
          containerRef={ref}
          contextMenu={nodeContextMenu}
          ids={interaction.selectedNodesIds}
          instance={nodeContextMenuInstance}
          setInstance={setNodeContextMenuInstance}
          editorInstance={editor}
          onOpened={(opened) => {
            interaction.contextMenuOpen = opened;
          }}
        />
      )}

      <div
        className="function-junctions-nodes-zoom"
        style={{
          transformOrigin: `${position.originX}px ${position.originY}px`,
          scale: position.scale,
          transform: `${getMatrix({
            scale: position.scale,
            translateX: position.translateX,
            translateY: position.translateY,
          })}`,
          touchAction: 'none',
        }}
        ref={ref}
      >
        <Connections editor={editor} />
        {Object.keys(nodes).map((key) => {
          if (nodes[key] && nodesState[key])
            return (
              <Node
                title={nodes[key].type}
                id={key}
                key={key}
                component={nodes[key].component}
                inputs={nodes[key].inputs}
                outputs={nodes[key].outputs}
                coordinates={{
                  x: nodes[key].x,
                  y: nodes[key].y,
                }}
                color={nodes[key].color}
                className={`${nodes[key].className ?? ''} ${
                  !interactable ? 'function-junction-node-disabled' : ''
                }`}
                updateNodes={updateNodes}
                style={nodes[key].style}
                selected={interaction.selectedNodesIds.some(
                  (selectedNodeId) => key === selectedNodeId,
                )}
                cloneable={nodes[key].cloneable}
                deletable={nodes[key].deletable}
                nodeControlButtons={nodeControlButtons}
                editor={editor}
                store={nodesState[key].store}
                onMouseDown={({ nativeEvent }) => interaction.dragNode(nativeEvent, key)}
                onTouchStart={({ nativeEvent }) => interaction.dragNode(nativeEvent, key)}
                onContextMenu={({ nativeEvent }) =>
                  interaction.openNodeContextMenu(nativeEvent, key)
                }
              />
            );
        })}
      </div>
    </div>
  );
};

export default Nodes;
