// packages/react/src/library/Connections/Connections.tsx
import React from 'react';
import { getConnections } from 'core/components/Connections';
import { Editor, Point } from 'core/types';
import { useReadable } from '../Hooks';
import Connection from '../Connection/Connection';

export type ConnectionsProps = {
  editor: Editor;
};

const Connections = ({ editor }: ConnectionsProps) => {
  const { position: positionStore } = editor;
  const { current: nodesStore } = editor.nodes;
  const { restored: restoredStore } = editor.state;
  const { state: liveConnectionStore, show: showLiveConnectionStore } = editor.connection;

  const [connections, setConnections] = React.useState<{ p1: Point; p2: Point }[]>();

  const position = useReadable(positionStore);
  const nodes = useReadable(nodesStore);
  const restored = useReadable(restoredStore);
  const liveConnection = useReadable(liveConnectionStore);
  const showLiveConnection = useReadable(showLiveConnectionStore);

  React.useEffect(() => {
    getConnections(nodes)
      .then((newConnections) => {
        setConnections(newConnections);
      })
      .catch(() => console.error('Failed to get connections'));
  }, [restored, nodes, liveConnection, position]);

  return (
    <div className="function-junctions-connections">
      {connections?.map((connection, index) => (
        <Connection key={index} connection={connection} />
      ))}

      {showLiveConnection && liveConnection?.points ? (
        <Connection connection={liveConnection.points} />
      ) : (
        <></>
      )}
    </div>
  );
};

export default Connections;

// packages/svelte/src/library/components/Connections/Connections.svelte
<script lang="ts">
  import type { Point } from 'core/types';
  import type { Editor } from 'core/components/Editor';
  import { getConnections } from 'core/components/connections';

  import Connection from '../Connection/Connection.svelte';

  export let editor: Editor;

  const { position } = editor;
  const { current: nodes } = editor.nodes;
  const { restored } = editor.state;
  const { state: liveConnection, show: showLiveConnection } = editor.connection;

  let connections: { p1: Point; p2: Point }[] = [];

  $: $restored,
    $nodes,
    $liveConnection,
    $position,
    getConnections($nodes)
      .then((newConnections) => {
        connections = newConnections;
      })
      .catch(() => console.error('Failed to get connections'));
</script>

<div class="function-junctions-connections">
  {#each connections as connection}
    <Connection {connection} />
  {/each}

  {#if $showLiveConnection}
    {#if $liveConnection?.points}
      <Connection connection={$liveConnection.points} />
    {/if}
  {/if}
</div>
