// packages/react/src/library/Nodes/Nodes.tsx
import React from 'react';
import {
  ContextMenu,
  EditorContextMenuProp,
  NodeContextMenuProp,
} from 'core/components/ContextMenu';
import { NodeControlButtons } from 'core/components/NodeButton';
import { EditorState } from 'core/types';
import { ReactEditor } from '../Editor';
import { useReadable, useWritable } from '../Hooks';
import { Interaction } from 'core/components/Interaction';
import Drag, { getMatrix } from 'core/components/Drag';
import EditorContextMenu from '../ContextMenu/EditorContextMenu';
import Node from '../Node/Node';
import NodeContextMenu from '../ContextMenu/NodeContextMenu';
import Connections from '../Connections/Connections';

export type NodesProps = {
  editor: ReactEditor;
  state: EditorState | undefined;
  setState: React.Dispatch<React.SetStateAction<EditorState | undefined>>;

  multiselect: boolean;
  zoomable: boolean;
  pannable: boolean;
  moveable: boolean;
  interactable: boolean;
  nodeControlButtons: NodeControlButtons | boolean;

  editorContextMenu: EditorContextMenuProp;
  nodeContextMenu: NodeContextMenuProp;

  onReady: ((editor: ReactEditor) => void) | undefined;
};

const Nodes = ({
  editor,
  setState,
  multiselect,
  zoomable,
  pannable,
  moveable,
  interactable,
  nodeControlButtons,
  editorContextMenu,
  nodeContextMenu,
  onReady,
}: NodesProps) => {
  const ref = React.useRef<HTMLDivElement>(null);

  const { position: positionStore } = editor;
  const { current: nodesStore } = editor.nodes;
  const { restored: stateRestoredStore, nodes: nodesStateStore } = editor.state;
  const { show: showLiveConnectionStore, state: liveConnectionStateStore } = editor.connection;

  const position = useReadable(positionStore);
  const nodes = useReadable(nodesStore);

  const stateRestored = useReadable(stateRestoredStore);
  const nodesState = useReadable(nodesStateStore);

  const [, setShowLiveConnection] = useWritable(showLiveConnectionStore);
  const liveConnectionState = useReadable(liveConnectionStateStore);

  const interaction = React.useMemo(
    () =>
      new Interaction(nodesStore, positionStore, undefined, {
        multiselect,
        zoomable,
        pannable,
        moveable,
      }),
    [moveable, multiselect, nodesStore, pannable, positionStore, zoomable],
  );

  const [editorContextMenuInstance, setEditorContextMenuInstance] = React.useState<ContextMenu>();
  const [nodeContextMenuInstance, setNodeContextMenuInstance] = React.useState<ContextMenu>();

  const hideLiveConnection = React.useCallback(
    () => liveConnectionState && setShowLiveConnection(false),
    [liveConnectionState, setShowLiveConnection],
  );

  React.useEffect(() => {
    if (stateRestored) editor.updateState();
  }, [nodes, stateRestored, editor]);

  React.useEffect(
    () =>
      setState({
        nodes: nodesState,
        position,
      }),
    [position, setState],
  );

  React.useEffect(() => {
    if (stateRestored && onReady) onReady(editor);
  }, [onReady, editor, stateRestored]);

  React.useEffect(() => {
    if (ref.current)
      interaction.dragger = Drag({
        scaleSensitivity: 100,
        minScale: 0.1,
        maxScale: 30,
        element: ref.current,
        transformation: positionStore,
      });
  }, [interaction, positionStore, ref]);

  React.useEffect(() => {
    if (editorContextMenuInstance && editorContextMenu)
      interaction.editorContextMenu = (() => {
        if (typeof editorContextMenu === 'function')
          return { type: 'callback', callback: editorContextMenu };
        return {
          type: 'instance',
          instance: editorContextMenuInstance,
          blueprint: editorContextMenu,
        };
      })();
    if (nodeContextMenuInstance && nodeContextMenu)
      interaction.nodeContextMenu = (() => {
        if (typeof nodeContextMenu === 'function')
          return { type: 'callback', callback: nodeContextMenu };
        return {
          type: 'instance',
          instance: nodeContextMenuInstance,
          blueprint: nodeContextMenu,
        };
      })();
  }, [
    editorContextMenu,
    editorContextMenuInstance,
    interaction,
    nodeContextMenu,
    nodeContextMenuInstance,
  ]);

  return (
    <div
      className="function-junctions-nodes"
      onClick={(event) => {
        hideLiveConnection();

        editorContextMenuInstance?.evaluate(event.nativeEvent);
        nodeContextMenuInstance?.evaluate(event.nativeEvent);
      }}
      onWheel={({ nativeEvent }) => interaction.zoom(nativeEvent)}
      onMouseDown={({ nativeEvent }) => interaction.startDrag(nativeEvent)}
      onMouseUp={interaction.endDrag}
      onMouseMove={({ nativeEvent }) => interaction.drag(nativeEvent)}
      onTouchStart={({ nativeEvent }) => interaction.startDrag(nativeEvent)}
      onTouchEnd={interaction.endDrag}
      onTouchMove={({ nativeEvent }) => interaction.touch(nativeEvent)}
      onContextMenu={({ nativeEvent }) => interaction.openEditorContextMenu(nativeEvent)}
    >
      {editorContextMenu && typeof editorContextMenu !== 'function' && (
        <EditorContextMenu
          containerRef={ref}
          contextMenu={editorContextMenu}
          instance={editorContextMenuInstance}
          setInstance={setEditorContextMenuInstance}
          editorInstance={editor}
          onOpened={(opened) => {
            interaction.contextMenuOpen = opened;
          }}
        />
      )}

      {nodeContextMenu && typeof nodeContextMenu !== 'function' && (
        <NodeContextMenu
          containerRef={ref}
          contextMenu={nodeContextMenu}
          ids={interaction.selectedNodesIds}
          instance={nodeContextMenuInstance}
          setInstance={setNodeContextMenuInstance}
          editorInstance={editor}
          onOpened={(opened) => {
            interaction.contextMenuOpen = opened;
          }}
        />
      )}

      <div
        className="function-junctions-nodes-zoom"
        style={{
          transformOrigin: `${position.originX}px ${position.originY}px`,
          scale: position.scale,
          transform: `${getMatrix({
            scale: position.scale,
            translateX: position.translateX,
            translateY: position.translateY,
          })}`,
          touchAction: 'none',
        }}
        ref={ref}
      >
        <Connections editor={editor} />
        {Object.keys(nodes).map((key) => {
          if (nodes[key] && nodesState[key])
            return (
              <Node
                title={nodes[key].type}
                id={key}
                component={nodes[key].component}
                inputs={nodes[key].inputs}
                outputs={nodes[key].outputs}
                coordinates={{
                  x: nodes[key].x,
                  y: nodes[key].y,
                }}
                color={nodes[key].color}
                className={`${nodes[key].className ?? ''} ${
                  !interactable ? 'function-junction-node-disabled' : ''
                }`}
                style={nodes[key].style}
                selected={interaction.selectedNodesIds.some(
                  (selectedNodeId) => key === selectedNodeId,
                )}
                cloneable={nodes[key].cloneable}
                deletable={nodes[key].deletable}
                nodeControlButtons={nodeControlButtons}
                editor={editor}
                store={nodesState[key].store}
                onMouseDown={({ nativeEvent }) => interaction.dragNode(nativeEvent, key)}
                onTouchStart={({ nativeEvent }) => interaction.dragNode(nativeEvent, key)}
                onContextMenu={({ nativeEvent }) =>
                  interaction.openNodeContextMenu(nativeEvent, key)
                }
              />
            );
        })}
      </div>
    </div>
  );
};

export default Nodes;

// src/library/components/Nodes/Nodes.svelte
<style lang="scss" global>
  @import './Nodes.scss';
</style>

<script lang="ts">
  import type { Editor, EditorState } from '../Editor';
  import Drag, { getMatrix } from '../Drag';
  import Node from '../Node/Node.svelte';
  import Connections from '../Connections/Connections.svelte';
  import type { Point } from '../../types';
  import type { EditorContextMenuBlueprint, NodeContextMenuBlueprint } from '../ContextMenu';
  import type { ContextMenu } from '../ContextMenu';
  import EditorContextMenu from '../ContextMenu/EditorContextMenu.svelte';
import NodeContextMenu from '../ContextMenu/NodeContextMenu.svelte';
  
  export let editor: Editor;
  export let state: EditorState | undefined;
  
  export let multiselect: boolean;
  export let zoomable: boolean;
  export let pannable: boolean;
  export let moveable: boolean;
  export let interactable: boolean;

  export let editorContextMenu: EditorContextMenuBlueprint | ((event: MouseEvent) => void) | undefined;
  export let nodeContextMenu: NodeContextMenuBlueprint | ((ids: string[], event: MouseEvent) => void )| undefined;

  export let onReady: ((editor: Editor) => void) | undefined = undefined;

  let ref: HTMLDivElement;

  const { position } = editor;
  const { current: nodes, selected: selectedNodesIds } = editor.nodes;
  const { restored: stateRestored, nodes: nodesState } = editor.state;
  const { show: showLiveConnection, state: liveConnectionState } = editor.connection;

  let nodeMoving = false;
  let containerMoving = false;
  let contextMenuOpen = false;

  let previousCoordinates: Point = {
    x: 0,
    y: 0,
  };
  let previousDistance: number;

  let editorContextMenuInstance: ContextMenu;
  let nodeContextMenuInstance: ContextMenu;

  const getCoordinates = (event: MouseEvent | TouchEvent) => {
    let pageX: number;
    let pageY: number;

    if ('touches' in event) {
      const touch = event.touches[0];

      pageX = touch.pageX;
      pageY = touch.pageY;
    } else {
      pageX = event.pageX;
      pageY = event.pageY;
    }

    return {
      pageX,
      pageY,
    };
  };

  const hideLiveConnection = () => $liveConnectionState && ($showLiveConnection = false);

  const zoom = (event: WheelEvent) => {
    if (zoomable) {
      event.preventDefault();

      const factor = 3.5;
      dragger.zoom({
        deltaScale: Math.sign(event.deltaY) > 0 ? -factor : factor,
        x: event.pageX,
        y: event.pageY,
      });
    }
  };

  const pinch = (event: TouchEvent) => {
    if (zoomable) {
      const [x1, y1] = [event.touches[0].pageX, event.touches[0].pageY];
      const [x2, y2] = [event.touches[1].pageX, event.touches[1].pageY];
  
      const distance = Math.hypot(x1 - x2, y1 - y2);
  
      if (typeof previousDistance !== 'undefined') {
        const x = (x1 + x2) / 2;
        const y = (y1 + y2) / 2;
        const factor = distance / 40;
        const delta = distance / previousDistance - 1;
    
        dragger.zoom({
          deltaScale: Math.sign(delta) > 0 ? factor : -factor,
          x,
          y,
        });
      }

      previousDistance = distance;
    }
  };

  const startDrag = (event: MouseEvent | TouchEvent) => {
    if (('button' in event) && event.button === 2) return;
    if (contextMenuOpen) return;

    const { pageX, pageY } = getCoordinates(event);

    previousCoordinates.x = pageX;
    previousCoordinates.y = pageY;

    containerMoving = true;
  };

  const endDrag = () => {
    nodeMoving = false;
    containerMoving = false;
  };

  const drag = (event: MouseEvent | TouchEvent) => {
    event.preventDefault();
    const { pageX, pageY } = getCoordinates(event);

    const movementX = pageX - (previousCoordinates?.x ?? 0);
    const movementY = pageY - (previousCoordinates?.y ?? 0);

    if (containerMoving && !nodeMoving && pannable) {
      dragger.panBy({
        originX: movementX,
        originY: movementY,
      });
    } else if (containerMoving && nodeMoving && $selectedNodesIds && moveable) {
      $selectedNodesIds.forEach((id) => {
        if ($selectedNodesIds.some((selectedNodeId) => id === selectedNodeId)) {
          const node = $nodes[id];

          // Get z coordinate to determine scale so nodes travel faster with scale
          const { scale } = $position;

          if (node) {
            nodes.update((prevNode) => ({
              ...prevNode,
              [id]: {
                ...node,
                x: node.x + movementX / scale,
                y: node.y + movementY / scale,
              },
            }));
          }
        }
      });
    }

    previousCoordinates.x = pageX; 
    previousCoordinates.y = pageY; 
  };

  const touch = (event: TouchEvent) => {
    event.preventDefault();
    
    if (event.touches.length === 2) {
      pinch(event);
    } else if (event.touches.length === 1) {
      drag(event);  
    }
  };

  const dragNode = (event: MouseEvent | TouchEvent, key: string) => {
    if (('button' in event) && event.button === 2) return;
    if (('touches' in event) && event.touches.length > 1) return;

    if (!moveable) return;
    if (containerMoving) return;
    if (contextMenuOpen) return;

    if (
      event.shiftKey
      && multiselect
      && !$selectedNodesIds.some((selectedNodeId) => key === selectedNodeId)
    ) {
      $selectedNodesIds = [...$selectedNodesIds, key];
    } else {
      $selectedNodesIds = [key];
    }
    
    nodeMoving = true;
  };

  $: dragger = Drag({
    scaleSensitivity: 100,
    minScale: .1,
    maxScale: 30,
    element: ref,
    transformation: position,
  });

  $: $nodes, (() => {
    if (stateRestored) editor.updateState();
  })();

  $: $nodesState, $position, state = {
    nodes: $nodesState,
    position: $position,
  };

  $: if (stateRestored && onReady) onReady(editor);
</script>

<div
  class="function-junctions-nodes"
  on:click={(event) => {
    hideLiveConnection();
    
    editorContextMenuInstance.evaluate(event);
    nodeContextMenuInstance.evaluate(event);
  }}
  on:wheel={zoom}
  on:mousedown={startDrag}
  on:mouseup={endDrag}
  on:mousemove={drag}
  on:touchstart={startDrag}
  on:touchend={endDrag}
  on:touchmove={touch}
  on:contextmenu={(event) => {
    nodeContextMenuInstance?.close();

    if (editorContextMenu) {
      event.preventDefault();

      if (typeof editorContextMenu === 'function') {
        editorContextMenu(event);
      } else {
        editorContextMenuInstance.open(event);
      }
    }
  }}
>
  {#if editorContextMenu && typeof editorContextMenu !== 'function'}
    <EditorContextMenu
      containerRef={ref}
      contextMenu={editorContextMenu}
      bind:instance={editorContextMenuInstance}
      bind:editorInstance={editor}
      bind:opened={contextMenuOpen}
    />
  {/if}

  {#if nodeContextMenu && typeof nodeContextMenu !== 'function'}
    <NodeContextMenu
      containerRef={ref}
      contextMenu={nodeContextMenu}
      ids={$selectedNodesIds}
      bind:instance={nodeContextMenuInstance}
      bind:editorInstance={editor}
      bind:opened={contextMenuOpen}
    />
  {/if}

  <div
    class="function-junctions-nodes-zoom"
    style={`
      transform-origin: ${$position.originX}px ${$position.originY}px;
      transform: ${getMatrix({
        scale: $position.scale,
        translateX: $position.translateX,
        translateY: $position.translateY,
      })};
      touch-action: none;
    `}
    bind:this={ref}
  >
    <Connections {editor} />
    {#each Object.keys($nodes) as key}
      <Node
        title={$nodes[key].type}
        id={key}
        component={$nodes[key].component}
        inputs={$nodes[key].inputs}
        outputs={$nodes[key].outputs}
        coordinates={{
          x: $nodes[key].x,
          y: $nodes[key].y,
        }}
        color={$nodes[key].color}
        className={`${$nodes[key].className ?? ''} ${!interactable ? 'function-junction-node-disabled' : ''}`}
        style={$nodes[key].style ?? ''}
        selected={$selectedNodesIds.some((selectedNodeId) => key === selectedNodeId)}
        {editor}
        bind:store={$nodesState[key].store}
        on:mousedown={(event) => dragNode(event, key)}
        on:touchstart={(event) => dragNode(event, key)}
        on:contextmenu={(event) => {
          editorContextMenuInstance?.close();

          $selectedNodesIds = [key];
          if (nodeContextMenu) {
            event.preventDefault();
            event.stopPropagation();
            
            if (typeof nodeContextMenu === 'function') {
              nodeContextMenu($selectedNodesIds, event);
            } else {
              nodeContextMenuInstance.open(event);
            }
          }
        }}
      />
    {/each}
  </div>
</div>
