// packages/react/src/library/components/ContextMenu/NodeContextMenu.tsx
import React from 'react';

import { NodeContextMenuBlueprint, ContextMenu as ContextMenuClass } from '@core/index';
import ContextMenuItem from './ContextMenuItem';
import ContextMenu from './ContextMenu';
import { Editor } from '../Editor';

export type NodeContextMenuProps = {
  ids: string[];
  editorInstance: Editor;
  instance: ContextMenuClass | undefined;
  contextMenu: NodeContextMenuBlueprint;
  containerRef: React.RefObject<HTMLDivElement>;
  setInstance: React.Dispatch<React.SetStateAction<ContextMenuClass | undefined>>;
  onOpened: (opened: boolean) => void;
};

const NodeContextMenu = ({
  ids,
  editorInstance,
  instance,
  contextMenu,
  containerRef,
  setInstance,
  onOpened,
}: NodeContextMenuProps) => {
  return (
    <ContextMenu
      containerRef={containerRef}
      instance={instance}
      setInstance={setInstance}
      onOpened={onOpened}
    >
      <ul onClick={() => instance?.close()}>
        {contextMenu.items && instance && (
          <>
            {contextMenu.items.map((item) => {
              return (
                <ContextMenuItem
                  key={item.type}
                  item={item}
                  ids={ids}
                  contextMenu={instance}
                  editor={editorInstance}
                />
              );
            })}
          </>
        )}
      </ul>
    </ContextMenu>
  );
};

export default NodeContextMenu;

// packages/svelte/src/library/components/ContextMenu/NodeContextMenu.svelte
<script lang="ts">
  import type { NodeContextMenuBlueprint, ContextMenu as ContextMenuType } from 'core/index';

  import ContextMenu from './ContextMenu.svelte';
  import ContextMenuItem from './ContextMenuItem.svelte';
  import type { Editor } from '../Editor';

  export let ids: string[];

  export let editorInstance: Editor;
  export let instance: ContextMenuType | undefined = undefined;

  export let contextMenu: NodeContextMenuBlueprint;

  export let containerRef: HTMLDivElement;

  export let opened = false;
</script>

<ContextMenu {containerRef} bind:instance bind:opened>
  <ul on:click={() => instance?.close()}>
    {#if contextMenu.items && instance}
      {#each contextMenu.items as item}
        <ContextMenuItem {item} {ids} contextMenu={instance} editor={editorInstance} />
      {/each}
    {/if}
  </ul>
</ContextMenu>
